title: WWT Contributor Hub
url: "https://worldwidetelescope.github.io"
email: wwt@aas.org
description: >-
  The hub for people who want to contribute to the WorldWide
  Telescope project.
twitter_username: wwtelescope
github_username: WorldWideTelescope
remote_theme: pmarsceill/just-the-docs
color_scheme: wwt

logo: "stacked-logo.png"

aux_links:
  "Source on GitHub!":
    - "//github.com/WorldWideTelescope/worldwidetelescope.github.io/"

footer_content: "Copyright 2019-2023 the .NET Foundation. WorldWide Telescope is a fiscally sponsored project of NumFOCUS, a nonprofit dedicated to supporting the open-source scientific computing community."

ga_tracking: UA-107473046-4

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
